// Generates the dev hand-off artifacts on the fly: CSS variables,
// design tokens (JSON), and a Tailwind preset (TypeScript).

type Scale = Record<string, string>

const COLORS_LIGHT: Record<string, Scale> = {
  gray: {
    1: '#FCFCFD', 2: '#F8F9FA', 3: '#F0F1F3', 4: '#E8E9EC', 5: '#DFE1E4', 6: '#D4D6DA',
    7: '#C2C5CA', 8: '#A9ADB4', 9: '#8B8F96', 10: '#808489', 11: '#60646C', 12: '#272A2E',
  },
  principal: {
    1: '#FBFDFF', 2: '#F4FAFF', 3: '#E6F4FE', 4: '#D5ECFD', 5: '#C2E1FC', 6: '#A9D3F7',
    7: '#8AC0EF', 8: '#5FA8E4', 9: '#0091FF', 10: '#0081E6', 11: '#006DCB', 12: '#113264',
  },
  red: {
    1: '#FFFCFC', 2: '#FFF7F7', 3: '#FEEBEC', 4: '#FFDBDC', 5: '#FFCDCE', 6: '#FDBDBE',
    7: '#F4A9AA', 8: '#EB8E90', 9: '#E5484D', 10: '#DC3D43', 11: '#CE2C31', 12: '#641723',
  },
  yellow: {
    1: '#FDFDF9', 2: '#FFFCE8', 3: '#FFFBD1', 4: '#FFF8BB', 5: '#FEF2A4', 6: '#F9E68C',
    7: '#EFD36C', 8: '#EBBC00', 9: '#F5D90A', 10: '#F7CE00', 11: '#946800', 12: '#35290F',
  },
  green: {
    1: '#FBFEFC', 2: '#F4FBF6', 3: '#E6F6EB', 4: '#D6F1DE', 5: '#C4E8D1', 6: '#AFDDC2',
    7: '#93CEAF', 8: '#65BA97', 9: '#46A758', 10: '#3E9B4F', 11: '#2A7E3B', 12: '#203C25',
  },
  teal: {
    1: '#FAFDFE', 2: '#F2FAFB', 3: '#DEF7F9', 4: '#CAF1F6', 5: '#B5E9F0', 6: '#9DDDE7',
    7: '#7DCEDC', 8: '#3DB9CF', 9: '#00A2C7', 10: '#0797B9', 11: '#107D98', 12: '#0D3C48',
  },
  violet: {
    1: '#FDFCFE', 2: '#FAF8FF', 3: '#F4F0FE', 4: '#EBE4FF', 5: '#E1D9FF', 6: '#D4CAFE',
    7: '#C2B5F5', 8: '#AA99EC', 9: '#6E56CF', 10: '#654DC4', 11: '#6550B9', 12: '#2F265F',
  },
}

const COLORS_DARK: Record<string, Scale> = {
  gray: {
    1: '#111214', 2: '#18191B', 3: '#212225', 4: '#28292D', 5: '#2F3035', 6: '#393A40',
    7: '#46484F', 8: '#5F6169', 9: '#6C6E76', 10: '#797B83', 11: '#B0B2B8', 12: '#EBEBED',
  },
  principal: {
    1: '#0D1520', 2: '#111B2A', 3: '#0D2847', 4: '#003362', 5: '#004074', 6: '#104D87',
    7: '#205D9E', 8: '#2870BD', 9: '#0090FF', 10: '#3B9EFF', 11: '#70B8FF', 12: '#C2E0FF',
  },
  red: {
    1: '#191111', 2: '#201314', 3: '#3B1219', 4: '#500F1C', 5: '#611623', 6: '#72232D',
    7: '#8C333A', 8: '#B54548', 9: '#E5484D', 10: '#EC5D5E', 11: '#FF9592', 12: '#FFD1D9',
  },
  yellow: {
    1: '#14120B', 2: '#1B180F', 3: '#2D2305', 4: '#362B00', 5: '#433500', 6: '#524202',
    7: '#665417', 8: '#836A21', 9: '#FFC53D', 10: '#FFFF57', 11: '#F5E147', 12: '#F6EEB4',
  },
  green: {
    1: '#0E1512', 2: '#121B17', 3: '#132D21', 4: '#113B29', 5: '#174937', 6: '#174933',
    7: '#174933', 8: '#2F7C57', 9: '#46A758', 10: '#55B467', 11: '#71D083', 12: '#C2F0C2',
  },
  teal: {
    1: '#0B161A', 2: '#101B20', 3: '#082C36', 4: '#003848', 5: '#004558', 6: '#045468',
    7: '#12677E', 8: '#11809C', 9: '#00A2C7', 10: '#23AFD0', 11: '#4CCCE6', 12: '#B6ECF7',
  },
  violet: {
    1: '#14121F', 2: '#1B1525', 3: '#291F43', 4: '#33255B', 5: '#3C2E69', 6: '#473876',
    7: '#56468B', 8: '#6958AD', 9: '#6E56CF', 10: '#7D66D9', 11: '#BAA7FF', 12: '#E2DDFE',
  },
}

const FONTS = {
  display: "'Archivo', sans-serif",
  heading: "'Archivo', sans-serif",
  body: "'Raleway', sans-serif",
  mono: "'JetBrains Mono', monospace",
} as const

const SCALE_ORDER = ['gray', 'principal', 'red', 'yellow', 'green', 'teal', 'violet'] as const

const generatedHeader = (kind: string) =>
  `/* ${kind} — generated by https://gcp-design-system.vercel.app\n` +
  `   Source of truth: src/styles/global.css */\n\n`

function colorVarsCss(scale: Scale, name: string): string {
  return Object.entries(scale)
    .map(([step, value]) => `  --${name}-${step}: ${value};`)
    .join('\n')
}

export function buildCss(): string {
  const lightBlock = SCALE_ORDER.map((s) => colorVarsCss(COLORS_LIGHT[s], s)).join('\n\n')
  const darkBlock = SCALE_ORDER.map((s) => colorVarsCss(COLORS_DARK[s], s)).join('\n\n')

  const fonts = Object.entries(FONTS)
    .map(([k, v]) => `  --font-${k}: ${v};`)
    .join('\n')

  const semantic = `  --background: var(--gray-1);
  --foreground: var(--gray-12);
  --muted: var(--gray-3);
  --muted-foreground: var(--gray-11);
  --border: var(--gray-6);
  --ring: var(--principal-9);
  --accent: var(--principal-9);
  --accent-foreground: #FFFFFF;
  --destructive: var(--red-9);
  --success: var(--green-9);
  --warning: var(--yellow-9);`

  return (
    generatedHeader('GCP Design System — CSS Variables') +
    `:root {\n${lightBlock}\n\n${semantic}\n\n${fonts}\n}\n\n` +
    `.dark {\n${darkBlock}\n}\n`
  )
}

export function buildTokensJson(): string {
  return JSON.stringify(
    {
      $description: 'GCP Design System tokens — Style Dictionary / Tokens Studio compatible.',
      $source: 'https://gcp-design-system.vercel.app',
      color: {
        light: COLORS_LIGHT,
        dark: COLORS_DARK,
      },
      typography: {
        fontFamilies: FONTS,
      },
    },
    null,
    2
  ) + '\n'
}

export function buildTailwindPreset(): string {
  const colorsExport = JSON.stringify(COLORS_LIGHT, null, 2)
  return (
    `// gcp-tailwind-preset.ts — drop into tailwind.config.{ts,js} via 'presets'.\n` +
    `// Generated from the GCP Design System.\n\n` +
    `import type { Config } from 'tailwindcss'\n\n` +
    `const colors = ${colorsExport} as const\n\n` +
    `export default {\n` +
    `  theme: {\n` +
    `    extend: {\n` +
    `      colors,\n` +
    `      fontFamily: {\n` +
    `        display: ['Archivo', 'sans-serif'],\n` +
    `        heading: ['Archivo', 'sans-serif'],\n` +
    `        body: ['Raleway', 'sans-serif'],\n` +
    `        mono: ['JetBrains Mono', 'monospace'],\n` +
    `      },\n` +
    `    },\n` +
    `  },\n` +
    `} satisfies Partial<Config>\n`
  )
}

export function buildReadme(): string {
  return `# GCP Design System — Hand-off

Generated from https://gcp-design-system.vercel.app

## Conteúdo

- \`tokens.css\` — variáveis CSS (light + dark) prontas pra :root.
- \`tokens.json\` — tokens estruturados (Style Dictionary / Tokens Studio).
- \`gcp-tailwind-preset.ts\` — preset pra dropar em \`tailwind.config.ts\`.

## Tipografia

- **Display & Heading**: Archivo (400–800)
- **Body**: Raleway (400–700)
- **Mono**: JetBrains Mono

Carregue do Google Fonts:
\`\`\`html
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800&family=Raleway:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
\`\`\`

## Uso (CSS)

\`\`\`html
<link rel="stylesheet" href="./tokens.css">
\`\`\`

\`\`\`css
.btn { background: var(--principal-9); color: var(--accent-foreground); }
\`\`\`

## Uso (Tailwind)

\`\`\`ts
// tailwind.config.ts
import gcpPreset from './gcp-tailwind-preset'
export default { presets: [gcpPreset] }
\`\`\`

## Uso (JSON Tokens)

\`\`\`ts
import tokens from './tokens.json'
const blue = tokens.color.light.principal['9']  // "#0091FF"
\`\`\`
`
}

function triggerDownload(content: BlobPart, filename: string, mime: string) {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export const handoffPackages = {
  css: () => triggerDownload(buildCss(), 'tokens.css', 'text/css;charset=utf-8'),
  json: () => triggerDownload(buildTokensJson(), 'tokens.json', 'application/json;charset=utf-8'),
  tailwind: () => triggerDownload(buildTailwindPreset(), 'gcp-tailwind-preset.ts', 'text/typescript;charset=utf-8'),
}

export async function downloadBundle() {
  const { default: JSZip } = await import('jszip')
  const zip = new JSZip()
  zip.file('README.md', buildReadme())
  zip.file('tokens.css', buildCss())
  zip.file('tokens.json', buildTokensJson())
  zip.file('gcp-tailwind-preset.ts', buildTailwindPreset())
  const blob = await zip.generateAsync({ type: 'blob' })
  triggerDownload(blob, 'gcp-design-system.zip', 'application/zip')
}
